### ISSUE TITLE
Update the arduino code for TMC2130 support

### ISSUE THREAD

**Issue by d-weber** [d-weber/prusa-chain-production#2]
The arduino code is actually made for A4988 drivers & 4 microswitch endstops

It should use TMC2130 stallguard function to detect endstops & detect ejection fails to retry

**Comment by Faceless3D** [comment]
Hi, 

thank you for this great project! I just finished the PCB and want to test the system. Do you know when the code for the TMC2130 Stepper is available? Unfortunetly i can´t code :( 

Thank you

**Comment by Faceless3D** [comment]
![WhatsApp Image 2020-11-07 at 13 44 07](https://user-images.githubusercontent.com/39437191/98441548-63520100-20ff-11eb-9068-ac9ec5fa08e7.jpeg)

**Comment by d-weber** [comment]
Great ! i'll update the code tonight

**Comment by d-weber** [comment]
Done, you mayd need to tune STALL_VALUE @Faceless3D

**Comment by Faceless3D** [comment]
Thank you! 

STALL_VALUE 9 works good for me. I also increased the acceleration a bit.

**Comment by d-weber** [comment]
Implemented in #9

**Comment by bnykolass** [comment]
Please, where should I put the script in octoprint?
It doesn't work for me as a plugin.
Well thank you
